from pathlib import Path
import json

import joblib
import numpy as np
import pandas as pd
import yaml
from sklearn.compose import ColumnTransformer
from sklearn.dummy import DummyRegressor
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from .features import add_features
from .ingest import load_data
from .preprocessing import clean_data
from .validation import quality_summary


NUMERIC_FEATURES = [
    "rsrp_dbm",
    "rsrq_db",
    "sinr_db",
    "rssi_dbm",
    "latency_ms",
    "packet_loss_pct",
    "handover_count",
    "hour",
    "day_of_week",
    "is_weekend",
    "signal_quality_score",
    "latency_signal_ratio",
    "loss_latency_interaction",
]

CATEGORICAL_FEATURES = ["network_type", "frequency_band", "cell_id"]


def load_config(path="config.yaml"):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def build_preprocessor():
    numeric = Pipeline(
        [
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ]
    )
    categorical = Pipeline(
        [
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore")),
        ]
    )
    return ColumnTransformer(
        [
            ("numeric", numeric, NUMERIC_FEATURES),
            ("categorical", categorical, CATEGORICAL_FEATURES),
        ]
    )


def evaluate(y_true, predictions):
    return {
        "MAE": round(float(mean_absolute_error(y_true, predictions)), 4),
        "RMSE": round(float(np.sqrt(mean_squared_error(y_true, predictions))), 4),
        "R2": round(float(r2_score(y_true, predictions)), 4),
    }


def write_report(results, path):
    rows = [
        "# Model Evaluation",
        "",
        "This file is generated by `python -m src.train`.",
        "",
        "| Model | MAE | RMSE | R² |",
        "|---|---:|---:|---:|",
    ]
    for name, metrics in results.items():
        rows.append(
            f"| {name} | {metrics['MAE']:.4f} | {metrics['RMSE']:.4f} | {metrics['R2']:.4f} |"
        )
    Path(path).write_text("\n".join(rows) + "\n", encoding="utf-8")


def main():
    cfg = load_config()
    raw = load_data(cfg["data"]["raw_path"])

    print("Raw data quality:")
    print(json.dumps(quality_summary(raw), indent=2))

    cleaned = add_features(clean_data(raw))
    processed_path = Path(cfg["data"]["processed_path"])
    processed_path.parent.mkdir(parents=True, exist_ok=True)
    cleaned.to_csv(processed_path, index=False)

    target = cfg["model"]["target"]
    features = NUMERIC_FEATURES + CATEGORICAL_FEATURES
    X = cleaned[features]
    y = cleaned[target]

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=cfg["model"]["test_size"],
        random_state=cfg["model"]["random_state"],
    )

    models = {
        "Mean Baseline": DummyRegressor(strategy="mean"),
        "Linear Regression": LinearRegression(),
        "Random Forest": RandomForestRegressor(
            n_estimators=250,
            max_depth=14,
            min_samples_leaf=2,
            random_state=cfg["model"]["random_state"],
            n_jobs=-1,
        ),
        "Gradient Boosting": GradientBoostingRegressor(
            n_estimators=180,
            learning_rate=0.05,
            max_depth=3,
            random_state=cfg["model"]["random_state"],
        ),
    }

    results = {}
    fitted = {}

    for name, estimator in models.items():
        pipe = Pipeline(
            [
                ("preprocessor", build_preprocessor()),
                ("model", estimator),
            ]
        )
        pipe.fit(X_train, y_train)
        predictions = pipe.predict(X_test)
        results[name] = evaluate(y_test, predictions)
        fitted[name] = pipe
        print(name, results[name])

    # Lowest RMSE determines the saved candidate.
    best_name = min(results, key=lambda name: results[name]["RMSE"])
    best_model = fitted[best_name]

    model_path = Path(cfg["output"]["model_path"])
    model_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(
        {
            "pipeline": best_model,
            "model_name": best_name,
            "features": features,
        },
        model_path,
    )

    metrics_path = Path(cfg["output"]["metrics_path"])
    metrics_path.parent.mkdir(parents=True, exist_ok=True)
    metrics_path.write_text(
        json.dumps({"best_model": best_name, "models": results}, indent=2),
        encoding="utf-8",
    )
    write_report(results, cfg["output"]["report_path"])

    print(f"\nBest model: {best_name}")
    print(f"Saved model -> {model_path}")


if __name__ == "__main__":
    main()
